---
language: python
python:
  - "3.6"
  - "3.7-dev"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install: "make"

script:
  - make test-readme
  - make ci

cache: pip

jobs:
  include:
    - stage: test
      script:
        - make test-readme
        - make test
    - stage: coverage
      python: 3.6
      script: codecov
