---
language: python
python:
  - "3.6"
  - "3.7-dev"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install: "make"

cache: pip

jobs:
  include:
    - stage: test
      script:
        - make test-readme
        - make test
