---
language: python
python:
  - 3.6
  # Python 3.7 does not seem to be supported by travisci as expected: https://github.com/travis-ci/travis-ci/issues/9815
  # - 3.7

before_install:
  - pip install setuptools

install:
  - python setup.py develop
  - pip install -r dev-requirements.txt

script:
  - pytest
